http:
  port: 8080
admin:
  port: 9876
  hostname: localhost
apiEndpoints:
  forumAPI:
    host: 'forum.example.com'
    paths:
      - '/discussions/*'
      - '/healthz'
  membersAPI:
    host: 'members.example.com'
serviceEndpoints:
  forumService:
    url: 'http://localhost:1337'
  membersService:
    url: 'http://localhost:1338'
policies:
  - expression
  - key-auth
  - proxy
pipelines:
  - name: forum
    apiEndpoints:
      - forumAPI
    policies:
      - expression:
        - action:
            jscode: |
              if (req.url.startsWith('/discussions')) {
                const slug = req.url.substr('/discussions'.length);
                req.url = '/d' + slug;
              }
      - proxy:
        - action:
            serviceEndpoint: forumService
  - name: members
    apiEndpoints:
      - membersAPI
    policies:
      - key-auth:
      - proxy:
        - action:
            serviceEndpoint: membersService